out-dir: ./dist

base-uri: dev.gaijin.team/go

packages:
  - name: "golib"
    description: 📦An all-purpose packages library.
    source:
      vcs-type: "git"
      vcs-uri: "https://github.com/GaijinEntertainment/golib"
      uri: "https://github.com/GaijinEntertainment/golib"
      dir-uri: "https://github.com/GaijinEntertainment/golib{/dir}"
      file-uri: "https://github.com/GaijinEntertainment/golib{/dir}/{file}#L{line}"
    private-source:
      vcs-type: "git"
      vcs-uri: "git+ssh://github.com/GaijinEntertainment/golib"

  - name: "go-exhaustruct"
    description: golang analyzer that finds structures with uninitialized fields
    source:
      vcs-type: "git"
      vcs-uri: "https://github.com/GaijinEntertainment/go-exhaustruct"
      uri: "https://github.com/GaijinEntertainment/go-exhaustruct"
      dir-uri: "https://github.com/GaijinEntertainment/go-exhaustruct{/dir}"
      file-uri: "https://github.com/GaijinEntertainment/go-exhaustruct{/dir}/{file}#L{line}"

    private-source:
      vcs-type: "git"
      vcs-uri: "git+ssh://github.com/GaijinEntertainment/go-exhaustruct"

  - name: "go-nakedefer"
    description: golang analyzer that finds deferred calls that seems to be erroneous
    source:
      vcs-type: "git"
      vcs-uri: "https://github.com/GaijinEntertainment/go-nakedefer"
      uri: "https://github.com/GaijinEntertainment/go-nakedefer"
      dir-uri: "https://github.com/GaijinEntertainment/go-nakedefer{/dir}"
      file-uri: "https://github.com/GaijinEntertainment/go-nakedefer{/dir}/{file}#L{line}"

    private-source:
      vcs-type: "git"
      vcs-uri: "git+ssh://github.com/GaijinEntertainment/go-nakedefer"