name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    strategy:
      matrix:
        go-version: [ "1.23" ]
        os: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.os }}
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - uses: actions/checkout@v4
      - name: "Lint"
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true
          args: --timeout 5m --issues-exit-code 0