name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    strategy:
      matrix:
        go-version: [ stable ]
        os: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.os }}
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - uses: actions/checkout@v4
      - name: "Lint"
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: true
          args: --timeout 5m --issues-exit-code 0


  dependabot-merge:
    name: "Dependabot auto-merge"
    runs-on: ubuntu-latest
    needs: [ "lint" ]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.11.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
